### ISSUE TITLE
글 "로컬 AI 시대의 여명" 안의 링크들이 404가 뜹니다.

### ISSUE THREAD

**Issue by xnuk** [wooseopkim/blog#23]
글 "[로컬 AI 시대의 여명]"의 내용 중에서:

> 일전에 [썼던 글][잘못된 링크]에 대한 follow-up으로 글을 하나 더 써보고자 한다.

> 어쩌면 [정말로 오픈 소스가 상용 모델들을 이기는 날이 올지도][잘못된 링크] 모른다.

이 두 부분의 링크가 `./ai-현황에-관한-사견`으로 되어 있고, 블로그 글들의 URL이 끝에 슬래시(`/`)를 다는 쪽으로 redirect하고 있기 때문에, 따라서 `/posts/로컬-ai-시대의-여명/ai-현황에-관한-사견`이라는 없는 글을 가리키게 됩니다.

비슷하게 같은 블로그 글을 링크하는 글 "[미노타쿤이 옳아]"에서:

> 누누히 말하지만, 누누히 말했는지는 모르겠고 [이 글][AI 현황에 관한 사견] 말미에서 암시한 바와 같이, 원어를 아는 것은 무엇보다 중요하다.

이 부분은 절대경로(`https://blog.wooseop.kim/posts/ai-현황에-관한-사견/`)를 사용하여 문제가 없습니다.

[잘못된 링크]: https://blog.wooseop.kim/posts/%EB%A1%9C%EC%BB%AC-ai-%EC%8B%9C%EB%8C%80%EC%9D%98-%EC%97%AC%EB%AA%85/ai-%ED%98%84%ED%99%A9%EC%97%90-%EA%B4%80%ED%95%9C-%EC%82%AC%EA%B2%AC
[AI 현황에 관한 사견]: https://blog.wooseop.kim/posts/ai-%ED%98%84%ED%99%A9%EC%97%90-%EA%B4%80%ED%95%9C-%EC%82%AC%EA%B2%AC/
[미노타쿤이 옳아]: https://blog.wooseop.kim/posts/%EB%AF%B8%EB%85%B8%ED%83%80%EC%BF%A4%EC%9D%B4-%EC%98%B3%EC%95%84/
[로컬 AI 시대의 여명]: https://blog.wooseop.kim/posts/%EB%A1%9C%EC%BB%AC-ai-%EC%8B%9C%EB%8C%80%EC%9D%98-%EC%97%AC%EB%AA%85/

**Comment by wooseopkim** [comment]
Astro 기본 설정이
- dev: [`ignore`](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) (어떻게 해도 상관없음)
- prod: [`directory`](https://docs.astro.build/en/reference/configuration-reference/#buildformat) (디렉토리 형태로 결과물을 생성)

이렇게 되어 있어 로컬 기준으로만 봤던 게 깨졌던 경우네요. `astro.config.mjs` 수정해서 해결(`75a5bb72618596eaceee011c430ec17957b171d4`)했고 RSS 피드 생성 시에도 trailing slash가 들어가 있는데 옵션 줘서 빼는 쪽(`25055975512a59e4f801bcc64c16a47b771d558f`)으로 진행했습니다.

제보 감사합니다.

사실 없애는 쪽으로 일원화해서 정리하면 기존 링크들이 죄다 깨지는 문제가 있기는 한데요, 하꼬 블로그 게시물에 링크가 얼마나 걸렸을 것이며, 블로그 볼 법한 분들 중에 trailing slash 한 번 슬쩍 지워볼 만한 비율도 은근 있을 것 같아 그냥 선호하는 방향으로 진행했습니다.
